spring.application.name=backend-pedidos360
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/fd7c1051-f107-4307-a49d-b7901ba3e873/v2.0
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Auto-creación de tablas JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para inspección (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
