spring.application.name=backend-pedidos360
server.port=8080

# Configuración de Seguridad IDaaS (Azure AD / Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/fd7c1051-f107-4307-a49d-b7901ba3e873/v2.0

# Conexión a Base de Datos Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-green-dawn-b5vsoor7-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Cy5VaOuYr7gh
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect